# cat_maps.py
#
# Reference lookup tables for Melee enum integer codes.
# These are NOT used by extract.py (which reads .value directly from
# libmelee enums), but are kept here as human-readable documentation
# for interpreting the integer values in the output parquet files.
#
# Source: hohav/ssbm-data, melee.enums
#
# NOTE: Action state IDs are intentionally omitted here because Melee
# reuses IDs across characters (e.g., 351 = FOX_ILLUSION for Fox/Falco
# and SWORD_DANCE_2_MID for Marth). A flat name->int map cannot
# represent this without collisions. The (character, action) pair is
# unambiguous — consult melee.enums.Action for the full mapping.

# --------------------
# melee.enums.Stage -> integer codes
STAGE_MAP = {
    "NO_STAGE":             0,
    "FOUNTAIN_OF_DREAMS":   8,
    "YOSHIS_STORY":         6,
    "POKEMON_STADIUM":     18,
    "BATTLEFIELD":         24,
    "FINAL_DESTINATION":   25,
    "DREAMLAND":           26,
    "RANDOM_STAGE":        29,
}

# --------------------
# melee.enums.Character -> integer codes
CHARACTER_MAP = {
    "MARIO":                 0,
    "FOX":                   1,
    "CPTFALCON":             2,
    "DK":                    3,
    "KIRBY":                 4,
    "BOWSER":                5,
    "LINK":                  6,
    "SHEIK":                 7,
    "NESS":                  8,
    "PEACH":                 9,
    "POPO":                 10,
    "NANA":                 11,
    "PIKACHU":              12,
    "SAMUS":                13,
    "YOSHI":                14,
    "JIGGLYPUFF":           15,
    "MEWTWO":               16,
    "LUIGI":                17,
    "MARTH":                18,
    "ZELDA":                19,
    "YLINK":                20,
    "DOC":                  21,
    "FALCO":                22,
    "PICHU":                23,
    "GAMEANDWATCH":         24,
    "GANONDORF":            25,
    "ROY":                  26,
    "WIREFRAME_MALE":       29,
    "WIREFRAME_FEMALE":     30,
    "GIGA_BOWSER":          31,
    "SANDBAG":              32,
    "UNKNOWN_CHARACTER":   255,
}

# --------------------
# melee.enums.ProjectileType -> integer codes
PROJECTILE_TYPE_MAP = {
    "ARROW":                     64,
    "BEAMSWORD":                 12,
    "BOB_OMB":                    6,
    "BOWSER_FLAME":              100,
    "DR_MARIO_CAPE":              84,
    "DR_MARIO_CAPSULE":           49,
    "FALCO_LASER":                55,
    "FALCO_SHADOW":               57,
    "FIREFIGHTER":               124,
    "FIRE_ARROW":                 65,
    "FOX_LASER":                  54,
    "FOX_SHADOW":                 56,
    "GW_FIRE":                   116,
    "ICE_BLOCK":                 106,
    "IC_BLIZZARD":               107,
    "IC_UP_B":                   113,
    "JUDGE":                     120,
    "KIRBY_BOWSER_FLAME":        154,
    "KIRBY_CUTTER":               50,
    "KIRBY_DR_MARIO_FIRE":       131,
    "KIRBY_FALCO_LASER":         137,
    "KIRBY_FOX_LASER":           136,
    "KIRBY_HAMMER":               51,
    "KIRBY_IC_BLOCK":            133,
    "KIRBY_LINK_ARROW":          140,
    "KIRBY_LINK_ARROW_2":        142,
    "KIRBY_LUIGI_FIRE":          132,
    "KIRBY_MARIO_FIRE":          130,
    "KIRBY_PICHU_THUNDERJOLT_1": 149,
    "KIRBY_PICHU_THUNDERJOLT_2": 150,
    "KIRBY_PIKACHU_THUNDERJOLT_1":147,
    "KIRBY_PIKACHU_THUNDERJOLT_2":148,
    "KIRBY_PK_FLASH":            145,
    "KIRBY_PK_FLASH_EXPLOSION":  146,
    "KIRBY_SAMUS_CHARGESHOT":    151,
    "KIRBY_SAUSAGE":             155,
    "KIRBY_SHADOWBALL":          144,
    "KIRBY_SHEIK_NEEDLE_GROUND": 153,
    "KIRBY_SHEIK_NEEDLE_THROWN": 152,
    "KIRBY_TOAD_SPORE":          135,
    "KIRBY_YLINK_ARROW":         141,
    "KIRBY_YLINK_ARROW_2":       143,
    "KIRBY_YOSHI_TONGUE":        157,
    "LINK_ARROW":                 76,
    "LINK_BOMB":                  58,
    "LINK_BOOMERANG":             60,
    "LINK_HOOKSHOT":              62,
    "LUIGI_FIRE":                105,
    "MANHOLE":                   115,
    "MARIO_CAPE":                 83,
    "MARIO_FIREBALL":             48,
    "MR_SATURN":                   7,
    "NEEDLE_THROWN":              79,
    "NESS_BATT":                 101,
    "NESS_YOYO":                 102,
    "PARACHUTE":                 117,
    "PEACH_PARASOL":             103,
    "PESTICIDE":                 114,
    "PICHU_THUNDER":              82,
    "PICHU_THUNDERJOLT_1":        91,
    "PICHU_THUNDERJOLT_2":        92,
    "PIKACHU_THUNDER":            81,
    "PIKACHU_THUNDERJOLT_1":      89,
    "PIKACHU_THUNDERJOLT_2":      90,
    "PK_FIRE":                    66,
    "PK_FLASH_1":                 67,
    "PK_FLASH_2":                 68,
    "PK_FLASH_EXPLOSION":         78,
    "PK_THUNDER_HEAD":            69,
    "PK_THUNDER_TAIL_1":          70,
    "PK_THUNDER_TAIL_2":          71,
    "PK_THUNDER_TAIL_3":          72,
    "PK_THUNDER_TAIL_4":          73,
    "SAMUS_BOMB":                 93,
    "SAMUS_CHARGE_BEAM":          94,
    "SAMUS_GRAPPLE_BEAM":         96,
    "SAMUS_MISSLE":               95,
    "SAUSAGE":                   122,
    "SHADOWBALL":                112,
    "SHEIK_CHAIN":                97,
    "SHEIK_SMOKE":                85,
    "SPERKY":                    119,
    "TOAD_SPORE":                111,
    "TURNIP":                     99,
    "TURTLE":                    118,
    "UNKNOWN_PROJECTILE":        255,
    "YLINK_ARROW":                77,
    "YLINK_BOMB":                 59,
    "YLINK_BOOMERANG":            61,
    "YLINK_HOOKSHOT":             63,
    "YLINK_MILK":                123,
    "YOSHI_EGG_THROWN":           86,
    "YOSHI_STAR":                 88,
    "YOSHI_TONGUE":               87,
    "ZELDA_FIRE":                108,
    "ZELDA_FIRE_EXPLOSION":      109,
}
